#second, minute, hour, day of month, month, day(s) of week
#(*) means match any
#*/X means "every X"
#1,5 one and five, 1-5 one to five
#<minute> <hour> <day-of-month> <month> <day-of-week> <command>

spring:
  profiles:
    active: test1

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  devtools:
    add-properties: false

cron:
  zone: Europe/Istanbul
  book:
    rate: 5000
    time: "* */1 * * * *"
    enabled: false

server:
  servlet:
    context-path: /api

logging:
  level:
    web: debug
    sql: error
    root: info