spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false

server:
  port: 8090