spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: false

server:
  port: 8090