#second, minute, hour, day of month, month, day(s) of week
#(*) means match any
#*/X means "every X"
#1,5 one and five, 1-5 one to five
#<minute> <hour> <day-of-month> <month> <day-of-week> <command>
cron-book: "* */1 * * * *"
zone: Europe/Istanbul

server:
  servlet:
    context-path: /api
  port: 0

spring:
  datasource:
    # jdbc:h2:tcp://localhost:9090/mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: "h2"
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2
