spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:starter-schema-h2.sql
      data-locations: classpath:starter-data-h2.sql

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true

server:
  port: 8080