#second, minute, hour, day of month, month, day(s) of week
#(*) means match any
#*/X means "every X"
#1,5 one and five, 1-5 one to five
#<minute> <hour> <day-of-month> <month> <day-of-week> <command>

spring:
  profiles:
    active: test2

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cron-book: "* */1 * * * *"
zone: Europe/Istanbul

server:
  servlet:
    context-path: /api